version: '3.8'

services:
  frankenphp:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: frankenphp_app
    ports:
      - "8080:80"
    volumes:
      - ./:/app
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: mysql_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: your_database_name
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
